remote_theme: so-simple-theme@master
plugins:
- jekyll -remote-theme

title: Pitha Recognizer
description: An image classification API that classifies 20 traditional Bangladeshi Pitha varieties.

author:
  name: Sheikh Anandee Hasan